/*
  These action types are used to dispatch actions to the reducer.
*/

export const ADD_COLOR_PICKER = 'ADD_COLOR_PICKER';
export const REMOVE_COLOR_PICKER = 'REMOVE_COLOR_PICKER';
export const UPDATE_COLOR_SCALE = 'UPDATE_COLOR_SCALE';
export const REMOVE_COLOR_SCALE = 'REMOVE_COLOR_SCALE';
export const UPDATE_BUTTON_FIRST_DATA = 'UPDATE_BUTTON_FIRST_DATA';
export const UPDATE_BUTTON_SECOND_DATA = 'UPDATE_BUTTON_SECOND_DATA';
export const UPDATE_FORM_ELEMENTS_DATA = 'UPDATE_FORM_ELEMENTS_DATA';
export const UPDATE_BORDER_RADIUS_DATA = 'UPDATE_BORDER_RADIUS_DATA';
export const UPDATE_FONT_FAMILY_DATA = 'UPDATE_FONT_FAMILY_DATA';
