export const ADD_COLOR_PICKER = 'ADD_COLOR_PICKER';
export const REMOVE_COLOR_PICKER = 'REMOVE_COLOR_PICKER';
export const UPDATE_COLOR_SCALE = 'UPDATE_COLOR_SCALE';
export const ADD_COLOR_SCALE = 'ADD_COLOR_SCALE';
export const REMOVE_COLOR_SCALE = 'REMOVE_COLOR_SCALE';
